
CREATE DATABASE EJERCICIO_TECNICO_CANNVIA;

USE EJERCICIO_TECNICO_CANNVIA;

CREATE TABLE Categoria (
    Id INT PRYMARY KEY INDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(250),
    FechaCreacion DATETIME DEFAULT GETDATE(),
    Activo INT DEFAULT 1
);

CREATE TABLE Producto (
    Id INT PRYMARY KEY INDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(200) NOT NULL,
    Descripcion VARCHAR(1000),
    Unidades INT DEFAULT 0,
    IdCategoria INT FOREIGN KEY REFERENCES Categoria(Id),
    FechaCreacion DATETIME DEFAULT GETDATE(),
    Activo INT DEFAULT 1
);